 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/snippets_lists", type: :request do
  # SnippetsList. As you add validations to SnippetsList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SnippetsList.create! valid_attributes
      get snippets_lists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      snippets_list = SnippetsList.create! valid_attributes
      get snippets_list_url(snippets_list)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_snippets_list_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      snippets_list = SnippetsList.create! valid_attributes
      get edit_snippets_list_url(snippets_list)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SnippetsList" do
        expect {
          post snippets_lists_url, params: { snippets_list: valid_attributes }
        }.to change(SnippetsList, :count).by(1)
      end

      it "redirects to the created snippets_list" do
        post snippets_lists_url, params: { snippets_list: valid_attributes }
        expect(response).to redirect_to(snippets_list_url(SnippetsList.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SnippetsList" do
        expect {
          post snippets_lists_url, params: { snippets_list: invalid_attributes }
        }.to change(SnippetsList, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post snippets_lists_url, params: { snippets_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested snippets_list" do
        snippets_list = SnippetsList.create! valid_attributes
        patch snippets_list_url(snippets_list), params: { snippets_list: new_attributes }
        snippets_list.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the snippets_list" do
        snippets_list = SnippetsList.create! valid_attributes
        patch snippets_list_url(snippets_list), params: { snippets_list: new_attributes }
        snippets_list.reload
        expect(response).to redirect_to(snippets_list_url(snippets_list))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        snippets_list = SnippetsList.create! valid_attributes
        patch snippets_list_url(snippets_list), params: { snippets_list: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested snippets_list" do
      snippets_list = SnippetsList.create! valid_attributes
      expect {
        delete snippets_list_url(snippets_list)
      }.to change(SnippetsList, :count).by(-1)
    end

    it "redirects to the snippets_lists list" do
      snippets_list = SnippetsList.create! valid_attributes
      delete snippets_list_url(snippets_list)
      expect(response).to redirect_to(snippets_lists_url)
    end
  end
end
